### ISSUE TITLE
Turn the script into a workflow

### ISSUE THREAD

**Issue by xilopaint** [CarlosEvo/alfred-emoji#1]
This is a great idea. Why don't you make it a workflow so we don't need to use Terminal?

**Comment by zoenglinghou** [comment]
There are some considerations:

## Python
1. It uses `python3`, which is not distributed with `macOS`. It might be a difficult for general users to install `python3` if they just wanna use the workflow.
2. I have no experience dealing with Unicode in `python2`. (No experience with `python2` tbh)
3. `python3` acts REALLY REALLY REALLY weird in workflow environments in terms of Unicode. I am having troubles dealing with German characters in my own workflows.

## Alfred design philosophies
1. IMO Alfred workflow is great for streamlining repetitive workflows, but emojis do not update really often.
2. This are really only 1-2 step(s) in this process - run the script, and open the file. A workflow seems a little redundant.

I would really appreciate a PR that convert the script into a `python2` script or Workflow tho...
